<a href="https://colab.research.google.com/github/2303A51069/B16_1069_PDS/blob/main/Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import numpy as np

In [44]:
A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

Matrix A:
 [[6 7 7]
 [8 2 2]
 [1 7 6]]

Matrix B:
 [[4 7 2]
 [6 3 6]
 [8 3 5]]


In [45]:
add_result = np.add(A, B)
sub_result = np.subtract(A, B)

In [46]:
print("Matrix A:\n", A)

Matrix A:
 [[6 7 7]
 [8 2 2]
 [1 7 6]]


In [47]:
print("Matrix B:\n", B)

Matrix B:
 [[4 7 2]
 [6 3 6]
 [8 3 5]]


In [48]:
print("\nAddition Result:\n", add_result)


Addition Result:
 [[10 14  9]
 [14  5  8]
 [ 9 10 11]]


In [49]:
print("\nSubtraction Result:\n", sub_result)


Subtraction Result:
 [[ 2  0  5]
 [ 2 -1 -4]
 [-7  4  1]]


In [50]:

print(f"A[0][0] + B[0][0] = {A[0][0]} + {B[0][0]} = {add_result[0][0]}")
print(f"A[0][0] - B[0][0] = {A[0][0]} - {B[0][0]} = {sub_result[0][0]}")

A[0][0] + B[0][0] = 6 + 4 = 10
A[0][0] - B[0][0] = 6 - 4 = 2


2)2D Matrix Multiplication

In [51]:
import numpy as np

image = np.array([
    [[123, 50, 200],
     [34, 210, 89],
     [255, 180, 75]],

    [[45, 60, 90],
     [220, 130, 40],
     [10, 240, 180]],

    [[100, 200, 150],
     [60, 90, 120],
     [80, 160, 220]]
], dtype=np.uint8)

In [52]:
print("Original Image (3x3x3):\n", image)

Original Image (3x3x3):
 [[[123  50 200]
  [ 34 210  89]
  [255 180  75]]

 [[ 45  60  90]
  [220 130  40]
  [ 10 240 180]]

 [[100 200 150]
  [ 60  90 120]
  [ 80 160 220]]]


In [53]:
red_layer = image[:, :, 0]
green_layer = image[:, :, 1]
blue_layer = image[:, :, 2]

print("\nRed Channel:\n", red_layer)
print("\nGreen Channel:\n", green_layer)
print("\nBlue Channel:\n", blue_layer)


Red Channel:
 [[123  34 255]
 [ 45 220  10]
 [100  60  80]]

Green Channel:
 [[ 50 210 180]
 [ 60 130 240]
 [200  90 160]]

Blue Channel:
 [[200  89  75]
 [ 90  40 180]
 [150 120 220]]


In [54]:
avg_red = np.mean(red_layer)
avg_green = np.mean(green_layer)
avg_blue = np.mean(blue_layer)

print("\nAverage Intensities:")
print(f"Red: {avg_red:.2f}, Green: {avg_green:.2f}, Blue: {avg_blue:.2f}")


Average Intensities:
Red: 103.00, Green: 146.67, Blue: 129.33


In [55]:
brightened = np.clip(image + 50, 0, 255)
print("\nBrightened Image:\n", brightened)


Brightened Image:
 [[[173 100 250]
  [ 84   4 139]
  [ 49 230 125]]

 [[ 95 110 140]
  [ 14 180  90]
  [ 60  34 230]]

 [[150 250 200]
  [110 140 170]
  [130 210  14]]]


In [56]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# 1D Array
b = np.array([10, 20, 30])

# Broadcasting (2D + 1D)
C = A + b
print("2D + 1D Broadcasting:\n", C)

2D + 1D Broadcasting:
 [[11 22 33]
 [14 25 36]]


In [57]:
D = np.ones((2,3,4)) * 5
scalar = 10
E = D + scalar
print("\n3D + scalar Broadcasting:\n", E)


3D + scalar Broadcasting:
 [[[15. 15. 15. 15.]
  [15. 15. 15. 15.]
  [15. 15. 15. 15.]]

 [[15. 15. 15. 15.]
  [15. 15. 15. 15.]
  [15. 15. 15. 15.]]]


In [58]:
b2 = np.array([1,2,3])
expanded = b2[:, np.newaxis]
print("\nShape Transformation Example:")
print("Original b2.shape:", b2.shape)
print("Expanded b2.shape:", expanded.shape)


Shape Transformation Example:
Original b2.shape: (3,)
Expanded b2.shape: (3, 1)


In [59]:
X = np.ones((2,3))
Y = np.ones((3,))
Z = X + Y
print("\n2D + 1D Broadcasting (Fixed Example):")
print("X shape:", X.shape)
print("Y shape:", Y.shape)
print("Result Z:\n", Z)


2D + 1D Broadcasting (Fixed Example):
X shape: (2, 3)
Y shape: (3,)
Result Z:
 [[2. 2. 2.]
 [2. 2. 2.]]
