<a href="https://colab.research.google.com/github/2303A51069/B16_1069_PDS/blob/main/Lab_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
import numpy as np


In [57]:
marks = np.array([
    [78, 85, 90],
    [92, 88, 76],
    [56, 67, 70],
    [89, 94, 91],
    [72, 60, 65]
])

In [58]:
print("Marks:\n", marks)

Marks:
 [[78 85 90]
 [92 88 76]
 [56 67 70]
 [89 94 91]
 [72 60 65]]


In [59]:
avg = np.mean(marks, axis=1)
print("Average:", avg)
print("Minimum:", np.min(marks))
print("Maximum:", np.max(marks))


Average: [84.33333333 85.33333333 64.33333333 91.33333333 65.66666667]
Minimum: 56
Maximum: 94


In [61]:
print("2nd student:", marks[1])


2nd student: [92 88 76]


In [63]:
print("Above 80:\n", marks[marks > 80])

Above 80:
 [85 90 92 88 89 94 91]


In [64]:
reshaped = marks.reshape(3, -1)
print("Reshaped:\n", reshaped)

Reshaped:
 [[78 85 90 92 88]
 [76 56 67 70 89]
 [94 91 72 60 65]]


2) Employee Salary Analysis with pandas DataFrame

In [65]:
import pandas as pd



In [66]:
data = {
    "Name": ["esha", "Arnav", "Ishika", "David", "Aira"],
    "ID": [101, 102, 103, 104, 105],
    "Department": ["HR", "IT", "Finance", "IT", "Marketing"],
    "Salary": [45000, 60000, 75000, 50000, 82000]
}

In [67]:
df = pd.DataFrame(data)
print("Employees:\n", df)

Employees:
      Name   ID Department  Salary
0    esha  101         HR   45000
1   Arnav  102         IT   60000
2  Ishika  103    Finance   75000
3   David  104         IT   50000
4    Aira  105  Marketing   82000


In [68]:
print("Salary > 50000:\n", df[df["Salary"] > 50000])

Salary > 50000:
      Name   ID Department  Salary
1   Arnav  102         IT   60000
2  Ishika  103    Finance   75000
4    Aira  105  Marketing   82000


In [69]:
print("Sorted:\n", df.sort_values(by="Salary", ascending=False))

Sorted:
      Name   ID Department  Salary
4    Aira  105  Marketing   82000
2  Ishika  103    Finance   75000
1   Arnav  102         IT   60000
3   David  104         IT   50000
0    esha  101         HR   45000


In [70]:
df["Bonus"] = df["Salary"] * 0.10
print("With Bonus:\n", df)

With Bonus:
      Name   ID Department  Salary   Bonus
0    esha  101         HR   45000  4500.0
1   Arnav  102         IT   60000  6000.0
2  Ishika  103    Finance   75000  7500.0
3   David  104         IT   50000  5000.0
4    Aira  105  Marketing   82000  8200.0


In [71]:
df["Total_Expense"] = df["Salary"] + df["Bonus"]
print("Total Expense:", df["Total_Expense"].sum())

Total Expense: 343200.0


In [72]:
df.to_csv("employee_salary_analysis.csv", index=False)
print("Saved to CSV")

Saved to CSV
